//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public long IdDetalle { get; set; }
        public Nullable<long> IdCompras { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<float> Costo { get; set; }
        public Nullable<float> Cantidad { get; set; }
        public Nullable<float> SubTotal { get; set; }
        public Nullable<float> Descuento { get; set; }
    
        public virtual COMPRAS COMPRAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
