//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEVENTA
    {
        public long idDetalle { get; set; }
        public float Cantidad { get; set; }
        public float precio { get; set; }
        public int IdDescuento { get; set; }
        public int idProducto { get; set; }
        public long idVenta { get; set; }
    
        public virtual DESCUENTOS DESCUENTO { get; set; }
        public virtual PRODUCTOS PRODUCTO { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
