//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.DETALLE_COMPRA = new HashSet<DETALLE_COMPRA>();
            this.VENCIMIENTOS = new HashSet<VENCIMIENTOS>();
            this.DETALLEVENTAS = new HashSet<DETALLEVENTA>();
        }
    
        public int idProductos { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> existencia { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idDescuentos { get; set; }
        public Nullable<double> costo { get; set; }
        public Nullable<bool> activo { get; set; }
        public string codigoBarra { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual DESCUENTOS DESCUENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMPRA> DETALLE_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENCIMIENTOS> VENCIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTAS { get; set; }
    }
}
