//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.COMPRAS = new HashSet<COMPRAS>();
        }
    
        public string Us_Usuario { get; set; }
        public string Us_Nombre { get; set; }
        public string Us_Apellido { get; set; }
        public string Us_Correo { get; set; }
        public Nullable<int> Us_Telefono { get; set; }
        public Nullable<int> Us_DUI { get; set; }
        public bool Us_Estado { get; set; }
        public string US_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAS> COMPRAS { get; set; }
    }
}
