//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENCIMIENTOS
    {
        public int idVencimiento { get; set; }
        public Nullable<int> idProductos { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
