//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA()
        {
            this.DETALLEVENTAS = new HashSet<DETALLEVENTA>();
        }
    
        public long IdVenta { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
        public string idUsuario { get; set; }
        public Nullable<bool> anulado { get; set; }
        public string motivo { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual CLIENTES CLIENTE { get; set; }
        public virtual Usuarios Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTAS { get; set; }
    }
}
