//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int IdVenta { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
        public string idUsuario { get; set; }
        public Nullable<bool> anulado { get; set; }
        public string motivo { get; set; }
        public string descripcion { get; set; }
        public string idCliente { get; set; }
    }
}
