//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaProductos
    {
        public int idProductos { get; set; }
        public string codigoBarra { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> existencia { get; set; }
        public string Categoria { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> costo { get; set; }
        public string Descuento { get; set; }
    }
}
